Problem statement

In the year 2000, the member states of the United Nations agreed to a set of goals to measure the progress of global development. The aim of these goals was to increase standards of living around the world by emphasizing human capital, infrastructure, and human rights.

The UN measures progress towards these goals using indicators such as percent of the population making over one dollar per day. Your task is to predict the change in these indicators one year and five years into the future. Predicting future progress will help us to understand how we achieve these goals by uncovering complex relations between these goals and other economic indicators. The UN set 2015 as the target for measurable progress. Given the data from 1972 - 2007, you need to predict a specific indicator for each of these goals in 2008 and 2012.

Import libraries

In [26]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Load and read files

In [27]:
#read files
#Reading train file:
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/UN_TrainingSet.csv')
#Reading sample submission file:
sample = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/UN_Submission.csv')

In [28]:
train

Unnamed: 0  ...                                        Series Name
0                0  ...  (%) Benefits held by 1st 20% population - All ...
1                1  ...  (%) Benefits held by 1st 20% population - All ...
2                2  ...  (%) Benefits held by 1st 20% population - All ...
3                4  ...             (%) Generosity of All Social Insurance
4                5  ...            (%) Generosity of All Social Protection
...            ...  ...                                                ...
195397      286113  ...  Women who believe a husband is justified in be...
195398      286114  ...  Women who believe a husband is justified in be...
195399      286115  ...  Women who believe a husband is justified in be...
195400      286116  ...  Women who believe a husband is justified in be...
195401      286117  ...  Women's share of population ages 15+ living wi...

[195402 rows x 40 columns]

Sample

This file is important! It contains the rows that you need to predict and the format for the predictions. Use the IDs in this file to extract the time series to predict from the Training Set.

In [29]:
sample

Unnamed: 0  2008 [YR2008]  2012 [YR2012]
0           559            NaN            NaN
1           618            NaN            NaN
2           753            NaN            NaN
3          1030            NaN            NaN
4          1896            NaN            NaN
..          ...            ...            ...
732      284474            NaN            NaN
733      285340            NaN            NaN
734      285399            NaN            NaN
735      285534            NaN            NaN
736      285811            NaN            NaN

[737 rows x 3 columns]

Merge sample with train

In [30]:
Train = pd.merge(train, sample, how='right')
Train

Unnamed: 0  1972 [YR1972]  ...  2008 [YR2008]  2012 [YR2012]
0           559            NaN  ...            NaN            NaN
1           618            NaN  ...            NaN            NaN
2           753         0.2960  ...            NaN            NaN
3          1030            NaN  ...            NaN            NaN
4          1896            NaN  ...            NaN            NaN
..          ...            ...  ...            ...            ...
732      284474            NaN  ...            NaN            NaN
733      285340            NaN  ...            NaN            NaN
734      285399            NaN  ...            NaN            NaN
735      285534         0.1087  ...            NaN            NaN
736      285811            NaN  ...            NaN            NaN

[737 rows x 42 columns]

In [31]:
train = Train.drop(['2008 [YR2008]', '2012 [YR2012]'], axis=1)
train

Unnamed: 0  ...                                        Series Name
0           559  ...                Ensure environmental sustainability
1           618  ...  Develop a global partnership for development: ...
2           753  ...                             Reduce child mortality
3          1030  ...                                    Combat HIV/AIDS
4          1896  ...                Ensure environmental sustainability
..          ...  ...                                                ...
732      284474  ...                                    Combat HIV/AIDS
733      285340  ...                Ensure environmental sustainability
734      285399  ...  Develop a global partnership for development: ...
735      285534  ...                             Reduce child mortality
736      285811  ...                                    Combat HIV/AIDS

[737 rows x 40 columns]

Create variables

In [32]:
ID = train['Unnamed: 0']
country_name = train['Country Name']
series_code = train['Series Code']
series_name = train['Series Name']

train = train.drop(['Unnamed: 0','Country Name', 'Series Code', 'Series Name'],axis=1)
train

1972 [YR1972]  1973 [YR1973]  ...  2006 [YR2006]  2007 [YR2007]
0              NaN            NaN  ...       0.430000         0.4650
1              NaN            NaN  ...       0.021071         0.0190
2           0.2960         0.2909  ...       0.114500         0.1115
3              NaN            NaN  ...       0.001000         0.0010
4              NaN            NaN  ...       0.962000         0.9610
..             ...            ...  ...            ...            ...
732            NaN            NaN  ...       0.136000         0.1340
733            NaN            NaN  ...       0.797000         0.7970
734            NaN            NaN  ...       0.097918         0.1085
735         0.1087         0.1083  ...       0.095800         0.0960
736            NaN            NaN  ...       0.173000         0.1640

[737 rows x 36 columns]

In [33]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 737 entries, 0 to 736
Data columns (total 36 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   1972 [YR1972]  172 non-null    float64
 1   1973 [YR1973]  170 non-null    float64
 2   1974 [YR1974]  170 non-null    float64
 3   1975 [YR1975]  179 non-null    float64
 4   1976 [YR1976]  186 non-null    float64
 5   1977 [YR1977]  192 non-null    float64
 6   1978 [YR1978]  195 non-null    float64
 7   1979 [YR1979]  200 non-null    float64
 8   1980 [YR1980]  201 non-null    float64
 9   1981 [YR1981]  213 non-null    float64
 10  1982 [YR1982]  219 non-null    float64
 11  1983 [YR1983]  219 non-null    float64
 12  1984 [YR1984]  226 non-null    float64
 13  1985 [YR1985]  229 non-null    float64
 14  1986 [YR1986]  235 non-null    float64
 15  1987 [YR1987]  227 non-null    float64
 16  1988 [YR1988]  230 non-null    float64
 17  1989 [YR1989]  231 non-null    float64
 18  1990 [YR19

In [34]:
train.shape

(737, 36)

Impute missing values

In [35]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer

imp = IterativeImputer(random_state=1)

train = imp.fit_transform(train)
train[train < 0] = 0
train.shape

(737, 36)

In [36]:
train

array([[0.        , 0.07481325, 0.        , ..., 0.395     , 0.43      ,
        0.465     ],
       [0.27305771, 0.17597141, 0.22986594, ..., 0.01224148, 0.02107124,
        0.019     ],
       [0.296     , 0.2909    , 0.2852    , ..., 0.1177    , 0.1145    ,
        0.1115    ],
       ...,
       [0.07749425, 0.12067247, 0.14993393, ..., 0.08015978, 0.09791841,
        0.1085    ],
       [0.1087    , 0.1083    , 0.1081    , ..., 0.0966    , 0.0958    ,
        0.096     ],
       [0.29635569, 0.16406746, 0.24595407, ..., 0.184     , 0.173     ,
        0.164     ]])

Define X, y and X_test

In [37]:
#split the dataset in two
# the last column is our label
y_train = train[:,-5:]
#drop last column of data
X_train = train[:, :-5]
#drop first colum of data
X_test = train[:,5:]
# lets have a look on the shape 
print(X_train.shape,y_train.shape,X_test.shape)

(737, 31) (737, 5) (737, 31)


In [38]:
X_train

array([[0.00000000e+00, 7.48132539e-02, 0.00000000e+00, ...,
        2.21000000e-01, 2.56000000e-01, 2.91000000e-01],
       [2.73057708e-01, 1.75971411e-01, 2.29865944e-01, ...,
        5.50137652e-02, 4.72000000e-05, 4.56000000e-05],
       [2.96000000e-01, 2.90900000e-01, 2.85200000e-01, ...,
        1.33900000e-01, 1.31000000e-01, 1.27700000e-01],
       ...,
       [7.74942520e-02, 1.20672465e-01, 1.49933927e-01, ...,
        4.01433500e-03, 7.99846000e-03, 3.99435610e-02],
       [1.08700000e-01, 1.08300000e-01, 1.08100000e-01, ...,
        1.02300000e-01, 1.01400000e-01, 1.00100000e-01],
       [2.96355687e-01, 1.64067458e-01, 2.45954066e-01, ...,
        2.57000000e-01, 2.43000000e-01, 2.28000000e-01]])

In [39]:
y_train

array([[0.325     , 0.36      , 0.395     , 0.43      , 0.465     ],
       [0.00087891, 0.00105809, 0.01224148, 0.02107124, 0.019     ],
       [0.1244    , 0.121     , 0.1177    , 0.1145    , 0.1115    ],
       ...,
       [0.06394787, 0.06564045, 0.08015978, 0.09791841, 0.1085    ],
       [0.0985    , 0.0973    , 0.0966    , 0.0958    , 0.096     ],
       [0.213     , 0.198     , 0.184     , 0.173     , 0.164     ]])

In [40]:
X_test

array([[0.02248484, 0.06614952, 0.04085576, ..., 0.395     , 0.43      ,
        0.465     ],
       [0.05795554, 0.08523337, 0.06270475, ..., 0.01224148, 0.02107124,
        0.019     ],
       [0.2683    , 0.2624    , 0.2565    , ..., 0.1177    , 0.1145    ,
        0.1115    ],
       ...,
       [0.06585548, 0.03505771, 0.00606963, ..., 0.08015978, 0.09791841,
        0.1085    ],
       [0.1077    , 0.1069    , 0.1053    , ..., 0.0966    , 0.0958    ,
        0.096     ],
       [0.29248319, 0.30760464, 0.3216563 , ..., 0.184     , 0.173     ,
        0.164     ]])

Define model

Imstall CatBoost

In [41]:
!pip install catboost

In [42]:
from sklearn.multioutput import MultiOutputRegressor
from catboost import CatBoostRegressor

model = MultiOutputRegressor(CatBoostRegressor(iterations=1000, depth=5, learning_rate=0.1, loss_function='RMSE')).fit(X_train, y_train)
print(model.score(X_train, y_train))

Streaming output truncated to the last 5000 lines.
1:	learn: 0.3170775	total: 12.4ms	remaining: 6.19s
2:	learn: 0.2892329	total: 17.7ms	remaining: 5.88s
3:	learn: 0.2631985	total: 22.9ms	remaining: 5.71s
4:	learn: 0.2411323	total: 28.1ms	remaining: 5.6s
5:	learn: 0.2198672	total: 33.4ms	remaining: 5.54s
6:	learn: 0.2007718	total: 38.8ms	remaining: 5.5s
7:	learn: 0.1838880	total: 44.2ms	remaining: 5.48s
8:	learn: 0.1685876	total: 49.4ms	remaining: 5.44s
9:	learn: 0.1543477	total: 54.9ms	remaining: 5.43s
10:	learn: 0.1413773	total: 60.2ms	remaining: 5.41s
11:	learn: 0.1305823	total: 65.5ms	remaining: 5.4s
12:	learn: 0.1201431	total: 70.8ms	remaining: 5.37s
13:	learn: 0.1112723	total: 75.9ms	remaining: 5.34s
14:	learn: 0.1032243	total: 81.2ms	remaining: 5.33s
15:	learn: 0.0953084	total: 86.3ms	remaining: 5.3s
16:	learn: 0.0883660	total: 91.6ms	remaining: 5.3s
17:	learn: 0.0819069	total: 97ms	remaining: 5.29s
18:	learn: 0.0763507	total: 102ms	remaining: 5.27s
19:	learn: 0.0710886	total: 10

Predict on train set

In [43]:
y_pred = model.predict(X_train)
y_pred

array([[3.24068768e-01, 3.59222923e-01, 3.93938540e-01, 4.29746913e-01,
        4.66198575e-01],
       [4.43176005e-04, 1.09602222e-03, 1.26049176e-02, 2.08304881e-02,
        1.98364503e-02],
       [1.24166400e-01, 1.20086506e-01, 1.15847987e-01, 1.08206895e-01,
        1.05097200e-01],
       ...,
       [6.34322784e-02, 6.47090516e-02, 8.01255309e-02, 9.68656952e-02,
        1.07772423e-01],
       [9.86841859e-02, 9.80663411e-02, 9.68721776e-02, 9.49470271e-02,
        9.48479125e-02],
       [2.13891299e-01, 1.98723532e-01, 1.84920731e-01, 1.74423604e-01,
        1.65516167e-01]])

Predict on test set

In [44]:
prediction = model.predict(X_test)
prediction[prediction < 0] = 0
prediction

array([[0.46327011, 0.47532245, 0.48016062, 0.52545648, 0.53154791],
       [0.03026232, 0.04019702, 0.06155066, 0.09174632, 0.12284057],
       [0.09458579, 0.08359615, 0.0846497 , 0.09178668, 0.08419369],
       ...,
       [0.14684242, 0.19310964, 0.23185903, 0.1992065 , 0.23686053],
       [0.09781427, 0.09026927, 0.08403843, 0.07943116, 0.0738292 ],
       [0.13307629, 0.13938631, 0.13932209, 0.12198894, 0.10591098]])

In [45]:
yr_2008 = prediction[:,0]
yr_2008

array([4.63270105e-01, 3.02623202e-02, 9.45857900e-02, 4.94667609e-03,
       9.53672108e-01, 1.64668725e-01, 2.27544238e-02, 9.57093833e-01,
       8.43054652e-01, 9.10298730e-02, 2.68525818e-02, 6.22195703e-01,
       2.99326094e-03, 5.26399513e-01, 1.10677869e-02, 1.91064390e-01,
       1.60581576e-02, 7.53115458e-01, 9.68202225e-01, 4.62731725e-01,
       1.01306564e-02, 9.70966164e-01, 3.05296441e-01, 1.56562743e-02,
       6.75155926e-03, 9.67199135e-01, 7.13647825e-02, 2.27792834e-02,
       4.94667609e-03, 9.58200272e-01, 3.98413074e-01, 9.48238045e-01,
       5.83121630e-01, 5.49450542e-03, 6.48400596e-01, 4.77277654e-03,
       8.49115606e-01, 8.43515923e-01, 2.39256328e-01, 4.48575679e-02,
       5.57240892e-03, 9.70927611e-01, 2.98820538e-01, 1.37804346e-02,
       3.09231765e-02, 3.89947355e-01, 9.80443557e-03, 8.70963041e-01,
       0.00000000e+00, 6.10224853e-02, 4.94667609e-03, 9.84714615e-01,
       6.87037998e-01, 1.51182241e-02, 1.40283732e-02, 9.80695830e-01,
      

In [46]:
yr_2012 = prediction[:,4]
yr_2012

array([5.31547910e-01, 1.22840574e-01, 8.41936938e-02, 2.33461604e-03,
       9.78082467e-01, 2.19137549e-01, 2.90548589e-02, 9.72901466e-01,
       8.52397764e-01, 1.73758146e-01, 3.97447133e-02, 6.61856251e-01,
       3.89022765e-03, 5.78780312e-01, 1.54161382e-04, 1.75140589e-01,
       1.19026134e-02, 7.65842377e-01, 9.87607010e-01, 6.14391094e-01,
       5.23390694e-03, 9.86262024e-01, 3.59478428e-01, 1.49596916e-02,
       0.00000000e+00, 9.84853820e-01, 1.72002787e-01, 2.24893525e-02,
       2.33461604e-03, 9.68359969e-01, 4.94653971e-01, 9.72616340e-01,
       6.44825409e-01, 5.08504784e-03, 6.69107119e-01, 4.85133484e-03,
       8.43037762e-01, 8.47316736e-01, 3.29671842e-01, 4.17092645e-02,
       9.37089721e-04, 9.89908308e-01, 4.24320725e-01, 1.59003566e-02,
       2.66820057e-02, 5.37435591e-01, 1.03679515e-02, 8.70772935e-01,
       0.00000000e+00, 5.08218119e-02, 2.33461604e-03, 9.92869513e-01,
       8.20413140e-01, 1.55939385e-02, 1.80059752e-03, 9.94728452e-01,
      

Prepare submission

In [47]:
# creating dataframe with required columns 
submission = pd.DataFrame({'Unnamed: 0':ID,'2008 [YR2008]':yr_2008,'2012 [YR2012]': yr_2012 })
# creating csv file from dataframe
submission.to_csv('submission.csv',index = False)
submission

Unnamed: 0  2008 [YR2008]  2012 [YR2012]
0           559       0.463270       0.531548
1           618       0.030262       0.122841
2           753       0.094586       0.084194
3          1030       0.004947       0.002335
4          1896       0.953672       0.978082
..          ...            ...            ...
732      284474       0.116520       0.117809
733      285340       0.829426       0.835609
734      285399       0.146842       0.236861
735      285534       0.097814       0.073829
736      285811       0.133076       0.105911

[737 rows x 3 columns]