taken from:-
https://martinfournier.com/how-to-normalize-and-denormalize-data-between-0-and-1/

Import libraries

In [ ]:
import numpy as np
import pandas as pd

Create dataframe

In [ ]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
d_min = min(data)
d_min

1

In [ ]:
d_max = max(data)
d_max

25

In [ ]:
d_mean = sum(data) / len(data)
d_mean

13.0

In [ ]:
d_std = np.std(data)
d_std

7.211102550927978

Normalise

In [ ]:
norm = (data - d_min) / (d_max - d_min)
norm

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

Denormalise

In [ ]:
denorm = (norm * (d_max - d_min) + d_min)
denorm

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

Standardise

In [ ]:
stan = (data - d_mean) / d_std
stan

array([-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039,
       -0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515,
       -0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ,
        0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534,
        1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059])

Destandardise

In [ ]:
destan = stan * d_std + d_mean
destan

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])